### ISSUE TITLE
Agregar otro algoritmo para comparar - anteproyecto

### ISSUE THREAD

**Issue by tatipar** [ElPelado619/ia-uncuyo-2023#1]
Considerar evaluar y comparar contra algoritmos genéticos u otra heurística.

**Comment by ElPelado619** [comment]
Con Gabriel, optamos por descartar la idea de usar Machine Learning para abordar nuestro problema, ya que excede lo que queríamos hacer inicialmente. Nuestro enfoque va a estar principalmente en CSP, y agregamos, como objetivo del proyecto, la construcción de un agente que usa un algoritmo genético para resolver el problema del Buscaminas, y la comparación de ambas estrategias. 

Los cambios hechos en el informe del anteproyecto fueron los siguientes:
- Cambio del código por "MS-CSP-GA".
- Cambio en la introducción.
- En la descripción de objetivos, se eliminó la construcción del agente con enfoque en Machine Learning y se agregó la construcción del agente con enfoque en Algoritmos Genéticos, junto a la justificación de la implementación del mismo en nuestro proyecto.

Con los puntos anteriores, cambió el cronograma de actividades a realizar, pero no se modificó la duración del mismo.

El informe está listo para su revisión.
